%#########################################################################
%#	 		 Masters Program in Computer Science - UFLA - 2016/1         #
%#                                                                       #
%# 					      Analysis Implementations                       #
%#                                                                       #
%#    Script responsible to manage the ".csv" analysis file processing   #
%#                                                                       #
%#                                                                       #
%# STUDENT                                                               #
%#                                                                       #
%#     João Paulo Fernanades de Cerqueira César                          #
%#                                                                       #
%# ADVISOR                                                               #
%#                                                                       #
%#     Wilian Soares Lacerda                                             #
%#                                                                       #
%#-----------------------------------------------------------------------#
%#                                                                       #
%# File: processStatistics.m                                             #
%#                                                                       #
%# About: This file describe a script which execute another scripts for  #
%#        statistical analysis of "pixel intensity", "entropy", "correla #
%#        tion", "differential" and "key sensitivity" in all the ".csv"  #
%#        files generated by "SIPI-USC" dataset processing. For each me  #
%#        tric will be generated a table with the processed data for     #
%#        each cryptosystem (Trivium, Grain and MICKEY).                 #
%#                                                                       #
%# 21/12/17 - Lavras - MG                                                #
%#########################################################################


% Call scripts for load the ".csv" paths.
configurePaths;

% Read all the ".csv" files to be processed.
readFilesCSV;

% Process the pixel average intensity.
processIntensity;

% Process the image entropy.
processEntropy;

% Process the image correlation.
processCorrelation;

% Process the differential analysis metrics.
processUACI;
processNPCR;

% Process the image key sensitivity.
processSensitivityCipher;
processSensitivityDecipher;

% Clear all the variables.
clear all;